### ISSUE TITLE
"Nebel" instead of "Neben" in German translation. 

### ISSUE THREAD

**Issue by Deevad** [Deevad/peppercarrot_ep17_translation#21]
Hey, 

I just received this comment on the blog, but I'm not expert to solve it:
![2016-21-07_selection_004](https://cloud.githubusercontent.com/assets/4021867/17037408/1772bf8e-4f91-11e6-8767-c805f9342c9d.png)
link: http://www.peppercarrot.com/en/article377/episode-17-a-fresh-start#c0377-361

I think  it's about this panel :+1: 
![2016-21-07_selection_005](https://cloud.githubusercontent.com/assets/4021867/17037444/3cd7b482-4f91-11e6-9945-56c76a9439f8.png)

Can you have a look at it @hapit ? thanks!

**Comment by hapit** [comment]
fixed issue with commit https://github.com/Deevad/peppercarrot_ep17_translation/commit/427c66d9ae82127e95bd9c5a336372f9c2472466
